In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("data.csv")

# Display the first 5 rows
print("--- First 5 Rows ---")
display(df.head())

# Display the last 5 rows
print("\n--- Last 5 Rows ---")
display(df.tail())

--- First 5 Rows ---

,Student_ID,Name,Gender,Age,Department,Math_Marks,Science_Marks,English_Marks,Attendance_Percentage,Date_of_Birth,Admission_Date,Email
0,ST001,Aarav Sharma,Male,20,Computer Science,85,78.0,92,88,2006-05-14,2023-08-01,aarav.sharma@gmail.com
1,ST002,Priya Patel,Female,19,Computer Science,72,81.0,76,91,2007-02-21,2023-08-01,priya.patel@gmail.com
2,ST003,Rohan Kumar,Male,21,Information Technology,45,52.0,48,65,2005-11-10,2022-08-05,rohan.kumar@gmail.com
3,ST004,Sneha Joshi,Female,20,IT,91,88.0,94,96,2006-07-18,2023-08-01,sneha.joshi@gmail.com
4,ST005,Vikram Singh,Male,22,Computer Science,38,42.0,35,58,2004-03-25,2021-08-02,vikram.singh@gmail.com

--- Last 5 Rows ---

,Student_ID,Name,Gender,Age,Department,Math_Marks,Science_Marks,English_Marks,Attendance_Percentage,Date_of_Birth,Admission_Date,Email
15,ST016,Pooja Deshmukh,Female,19,Data Science,90,85.0,88,95,2007-01-17,2024-08-01,pooja.d@gmail.com
16,ST017,Manish Yadav,Male,20,Computer Science,58,62.0,55,79,2006-03-31,2023-08-01,manish.yadav@gmail.com
17,ST018,Riya Kapoor,Female,21,Information Technology,71,74.0,70,84,2005-09-23,2022-08-05,riya.kapoor@gmail.com
18,ST019,Dev Patel,Male,20,Data Science,102,76.0,82,86,2006-06-11,2023-08-01,dev.patel@gmail.com
19,ST020,Simran Kaur,Female,20,Computer Science,66,NaN,75,81,2006-02-29,2023-08-01,simran.kaur@gmail.com

In [ ]:
# 1. Display total number of rows and columns
print("--- Total Rows & Columns ---")
print(df.shape)

# 2. Display data types of each column
print("\n--- Data Types ---")
print(df.dtypes)

--- Total Rows & Columns ---
(20, 12)

--- Data Types ---
Student_ID                object
Name                      object
Gender                    object
Age                        int64
Department                object
Math_Marks                 int64
Science_Marks            float64
English_Marks              int64
Attendance_Percentage      int64
Date_of_Birth             object
Admission_Date            object
Email                     object
dtype: object

In [ ]:
# 1. Count missing values per column
missing_counts = df.isnull().sum()

# 2. Filter and display only columns that have at least one missing value
print("--- Columns with Missing Values & Their Counts ---")
print(missing_counts[missing_counts > 0])

--- Columns with Missing Values & Their Counts ---
Science_Marks    1
dtype: int64

In [ ]:
# Loop through each column in the DataFrame
for col in df.columns:
    # Check if the column is numerical (integers or decimals)
    if df[col].dtype in ['int64', 'float64']:
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)

    # Check if the column is categorical (text or objects)
    elif df[col].dtype == 'object':
        # .mode()[0] gets the most frequent value in that column
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)

# Verify that all missing values are filled
print("--- Remaining Missing Values ---")
print(df.isnull().sum())

--- Remaining Missing Values ---
Student_ID               0
Name                     0
Gender                   0
Age                      0
Department               0
Math_Marks               0
Science_Marks            0
English_Marks            0
Attendance_Percentage    0
Date_of_Birth            0
Admission_Date           0
Email                    0
dtype: int64

In [ ]:
# 1. Check how many duplicates exist before removing them
print(f"Number of duplicate rows before: {df.duplicated().sum()}")

# 2. Remove duplicate rows
df = df.drop_duplicates()

# 3. Verify they are gone
print(f"Number of duplicate rows after: {df.duplicated().sum()}")
print(f"New total dataset size: {df.shape}")

Number of duplicate rows before: 0
Number of duplicate rows after: 0
New total dataset size: (20, 12)

In [ ]:
# Print all column names exactly as they are written
print(df.columns.tolist())

['Student_ID', 'Name', 'Gender', 'Age', 'Department', 'Math_Marks', 'Science_Marks', 'English_Marks', 'Attendance_Percentage', 'Date_of_Birth', 'Admission_Date', 'Email']

In [ ]:
# 1. Rename all columns to lowercase
df.columns = df.columns.str.lower()

# 2. Display the new column names
print("--- Updated Column Names ---")
print(df.columns.tolist())

--- Updated Column Names ---
['student_id', 'name', 'gender', 'age', 'department', 'math_marks', 'science_marks', 'english_marks', 'attendance_percentage', 'date_of_birth', 'admission_date', 'email']

In [ ]:
# 1. Automatically find and convert applicable float columns to integers
for col in df.columns:
    if df[col].dtype == 'float64':
        # Check if the column has no missing values
        if df[col].isnull().sum() == 0:
            df[col] = df[col].astype('int64')
            print(f"Converted column to integer: '{col}'")

# 2. Verify your updated data types
print("\n--- Current Data Types ---")
print(df.dtypes)

Converted column to integer: 'science_marks'

--- Current Data Types ---
student_id               object
name                     object
gender                   object
age                       int64
department               object
math_marks                int64
science_marks             int64
english_marks             int64
attendance_percentage     int64
date_of_birth            object
admission_date           object
email                    object
dtype: object

In [ ]:
# 1. Choose the specific columns you want to fill
columns_to_fill = ['math_marks', 'science_marks', 'english_marks']

# 2. Fill missing values in these columns with a specific value (e.g., 0)
df[columns_to_fill] = df[columns_to_fill].fillna(0)

# 3. Verify that these columns no longer have missing values
print("--- Remaining Missing Values ---")
print(df[columns_to_fill].isnull().sum())

--- Remaining Missing Values ---
math_marks       0
science_marks    0
english_marks    0
dtype: int64

In [ ]:
# 1. Define the columns you want to transform
marks_columns = ['math_marks', 'science_marks', 'english_marks']

# 2. Increase the marks by 10%
df[marks_columns] = df[marks_columns] * 1.10

# 3. View a few rows to confirm the updated scores
print("--- Updated Marks (First 5 Rows) ---")
display(df[marks_columns].head())

--- Updated Marks (First 5 Rows) ---

   math_marks  science_marks  english_marks
0        93.5           85.8          101.2
1        79.2           89.1           83.6
2        49.5           57.2           52.8
3       100.1           96.8          103.4
4        41.8           46.2           38.5

In [ ]:
# Multiply by 10%, round to the nearest whole number, and convert to integer
df[marks_columns] = (df[marks_columns] * 1.10).round(0).astype(int)

In [ ]:
# Convert all text in the column to UPPERCASE
df['department'] = df['department'].str.upper()

# Verify the changes
print(df['department'].unique())

['COMPUTER SCIENCE' 'INFORMATION TECHNOLOGY' 'IT' 'DATA SCIENCE']

In [ ]:
import numpy as np

# Define your passing threshold (e.g., 40 marks)
passing_score = 40

# 1. Option A: Pass/Fail based on the average score across all subjects
average_marks = (df['math_marks'] + df['science_marks'] + df['english_marks']) / 3

df['status'] = np.where(average_marks >= passing_score, 'Pass', 'Fail')

# 2. Option B: Pass ONLY if they score above the threshold in EVERY subject
# df['status'] = np.where(
#     (df['math_marks'] >= passing_score) &
#     (df['science_marks'] >= passing_score) &
#     (df['english_marks'] >= passing_score),
#     'Pass', 'Fail'
# )

# Check your results
print("--- Status Counts ---")
print(df['status'].value_counts())

print("\n--- Quick View ---")
display(df[['math_marks', 'science_marks', 'english_marks', 'status']].head())

--- Status Counts ---
status
Pass    20
Name: count, dtype: int64

--- Quick View ---

   math_marks  science_marks  english_marks status
0         124            113            134   Pass
1         106            119            111   Pass
2          65             76             70   Pass
3         133            129            138   Pass
4          56             62             51   Pass

In [ ]:
# 1. Filter students with marks > 80 (e.g., in Math)
high_math_scorers = df[df['math_marks'] > 80]

print("--- Students with Math Marks > 80 ---")
display(high_math_scorers[['name', 'department', 'math_marks']].head())


# 2. Filter data where Rainfall > 10
# (Uncomment and use this if you have a separate weather dataset loaded as 'df_weather')
# heavy_rain = df_weather[df_weather['rainfall'] > 10]


# 3. Alternative: Filter students who scored > 80 in ALL three subjects
excellent_students = df[(df['math_marks'] > 80) &
                        (df['science_marks'] > 80) &
                        (df['english_marks'] > 80)]

print("\n--- Students with > 80 in All Subjects ---")
display(excellent_students[['name', 'math_marks', 'science_marks', 'english_marks']].head())

--- Students with Math Marks > 80 ---

           name        department  math_marks
0  Aarav Sharma  COMPUTER SCIENCE         124
1   Priya Patel  COMPUTER SCIENCE         106
3   Sneha Joshi                IT         133
5  Ananya Gupta      DATA SCIENCE         129
6   Rahul Verma      DATA SCIENCE          98

--- Students with > 80 in All Subjects ---

           name  math_marks  science_marks  english_marks
0  Aarav Sharma         124            113            134
1   Priya Patel         106            119            111
3   Sneha Joshi         133            129            138
5  Ananya Gupta         129            132            125
6   Rahul Verma          98            105            100

In [ ]:
# 1. Define the list of columns you want to remove
columns_to_drop = ['email']

# 2. Drop the columns from the dataset
df = df.drop(columns=columns_to_drop)

# 3. Verify the columns were removed successfully
print("--- Remaining Columns ---")
print(df.columns.tolist())

--- Remaining Columns ---
['student_id', 'name', 'gender', 'age', 'department', 'math_marks', 'science_marks', 'english_marks', 'attendance_percentage', 'date_of_birth', 'admission_date', 'status']